export const ActionTypes = {
  GET_WEATHER: "GET_WEATHER",
  GET_TRAVEL_NEWS: " GET_TRAVEL_NEWS",
  GET_RECREATION_CENTRES: "GET_RECREATION_CENTRES",
  GET_WEATHER_ERROR: "GET_WEATHER_ERROR",
  GET_TRAVEL_NEWS_ERROR: " GET_TRAVEL_NEWS_ERROR",
  GET_RECREATION_CENTRES_ERROR: "GET_RECREATION_CENTRES_ERROR",
  FETCH_DATA_START: "FETCH_DATA_START",
  DESTINATION_NAME: "DESTINATION_NAME",
};
